更新 test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: 内核
+name: 内核编译
 
 permissions:
   contents: read
@@ -110,12 +110,10 @@ jobs:
           job_suffix_text=""
           SUKI_REPO_URL="https://github.com/ShirkNeko/SukiSU-Ultra.git"
           CLONE_BRANCH="main"
-          if [[ "${{ github.event.inputs.kernelsu_branch }}" == "Dev" ]]; then
-            CLONE_BRANCH="susfs-dev"
-          fi
           echo "Attempting to clone SukiSU from $SUKI_REPO_URL branch $CLONE_BRANCH..."
-          if git clone --branch "$CLONE_BRANCH" --single-branch "$SUKI_REPO_URL" SukiSU_temp_for_version; then
+          if git clone --branch "$CLONE_BRANCH" --single-branch --depth=100 "$SUKI_REPO_URL" SukiSU_temp_for_version; then
             cd SukiSU_temp_for_version
+            git fetch --unshallow || echo "Unshallow failed, proceeding anyway."
             release_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "notag")
             commit_hash=$(git rev-parse --short HEAD 2>/dev/null || echo "nohash")
             branch_name=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "nobranch")
